name: queries
version: 0.0.16
author: Andrew Mezoni <andrew.mezoni@gmail.com>
description: Queryable collections for Dart language.
homepage: https://github.com/mezoni/queries
dev_dependencies:
  build_tools: any
  file_utils: any
  unittest: any
